#!/bin/bash

mkdir -p .backup
timestamp=$(date +%s)
mkdir .backup/$timestamp
cp * .backup/$timestamp

pkill -9 avrdude
arduino --port /dev/$(ls /dev | grep ttyACM | head -n 1) --upload robocon2018.ino